Repository mattermost/mattermost-plugin-msteams-devsecops, pull requests merged in 2025-05, with the labels that each got.

#29 Docs update with screenshots
  README.md
  docs/Enterprise-to-Tactical-Edge-with-Mattermost-and-Microsoft.png
  docs/External-Collaboration-with-Enterprise-Control-Microsoft.png
  docs/admin_setup.md
  docs/install_plugin.md
  docs/remember-client-secret.png
  docs/remember-tenant-client.png
  docs/select-manage-apps.png
  docs/tenant-client-secret-sysconsole.png
  plugin.json
Labels: 2: Dev Review, documentation

#30 Fix readme: indicate beta; remove 'future' notices; address AI proof-reader issues
  README.md
  docs/admin_setup.md
Labels: 3: Reviews Complete

#40 Update permissions check for Azure app to include AppCatalog.Read.All
  server/credentials.go
Labels: 2: Dev Review

#43 MM-63941 - Fix bug where Mattermost sessions were only lasting an hour
  server/iframe.go
Labels: 2: Dev Review, 3: Security Review

#45 Update README.md
  README.md
Labels: 3: Reviews Complete

#46 Update admin_setup.md
  docs/admin_setup.md
Labels: 3: Reviews Complete

#47 Consolidate product docs & README
  README.md
  docs/Enterprise-to-Tactical-Edge-with-Mattermost-and-Microsoft.png
  docs/External-Collaboration-with-Enterprise-Control-Microsoft.png
  docs/admin_setup.md
  docs/install_plugin.md
  docs/remember-client-secret.png
  docs/remember-tenant-client.png
  docs/select-manage-apps.png
  docs/tenant-client-secret-sysconsole.png
Labels: 2: Dev Review

#52 Better product description for README
  README.md
  appstore/HUB/manifest.json
Labels: 3: Reviews Complete
